# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
      - '*-SNAPSHOT'
  pull_request:
    branches:
      - main
      - '*-SNAPSHOT'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '11' ]
    name: JDK ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Build Maven project (Modified for Linux Machine Specific JDK 11.0.17)
        run: ./mvnw --batch-mode verify --file pom.xml